fn_storage_account_name        =  "omnisa"
fn_app_service_plan_name       =  "omni-plan"
function_app_name              =  "omni-fn"
namespace_name                 =  "omni-namespace"
eventhub_name                  =  "omni-eventhub"
iothub_name                    =  "omni-iot"
connection_string              =  ""
container_name                 =  "omni-container"
